# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10n7wUOH3zFWlIOJPhpvfj54rfTMPWRc7
"""

pandas
numpy
google-play-scraper
nltk
Sastrawi
scikit-learn
tensorflow
keras
textblob
matplotlib
seaborn