# -*- coding: utf-8 -*-
"""scraping_playstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JVHM6KOpnwS0kvZKZBQ3GaYxvfw6jO6
"""

!pip install google-play-scraper
from google_play_scraper import reviews, Sort
import pandas as pd

all_reviews = []
count = 0

while count < 3000:
    result, _ = reviews(
        'com.shopee.id',
        lang='id',
        country='id',
        sort=Sort.NEWEST,
        count=200
    )
    all_reviews.extend(result)
    count = len(all_reviews)

df = pd.DataFrame(all_reviews)
df = df[['content', 'score']]

def label_sentiment(score):
    if score <= 2:
        return 'negatif'
    elif score == 3:
        return 'netral'
    else:
        return 'positif'

df['label'] = df['score'].apply(label_sentiment)
df.rename(columns={'content': 'review'}, inplace=True)

df.to_csv("dataset_scraping.csv", index=False)

print("Dataset berhasil dibuat:", len(df))

df = pd.read_csv("dataset_scraping.csv")
df.head()

!ls
df.info()

df['label'].value_counts()

df = df.dropna()
df.to_csv("dataset_scraping.csv", index=False)